jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 961341534133.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Docker image
      run: |
        docker build -t myapp:latest .
        docker tag myapp:latest 961341534133.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
        docker push 961341534133.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
