name: Build and Push Docker to AWS ECR

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main 
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 961341534133.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Docker image
      env:
        AWS_REGION: us-east-1
      run: |
        docker build -t myapp:latest .
        docker tag myapp:latest <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
        docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
